/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface OrderBookMarginInterface extends ethers.utils.Interface {
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "allHashes(uint256,uint256)": FunctionFragment;
    "createOrder((bytes32,uint256,address,uint256,uint256,address,address,uint256,bytes32,uint256,uint256,uint8,bytes32,bytes32))": FunctionFragment;
    "getTrader(bytes32)": FunctionFragment;
    "hashesOfCollateralToken(address,uint256,uint256)": FunctionFragment;
    "hashesOfTrader(address,uint256,uint256)": FunctionFragment;
    "numberOfAllHashes()": FunctionFragment;
    "numberOfHashesOfCollateralToken(address)": FunctionFragment;
    "numberOfHashesOfTrader(address)": FunctionFragment;
    "orderOfHash(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allHashes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      {
        loanId: BytesLike;
        leverageAmount: BigNumberish;
        loanTokenAddress: string;
        loanTokenSent: BigNumberish;
        collateralTokenSent: BigNumberish;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumberish;
        loanDataBytes: BytesLike;
        deadline: BigNumberish;
        createdTimestamp: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrader",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashesOfCollateralToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashesOfTrader",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfAllHashes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfHashesOfCollateralToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfHashesOfTrader",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "orderOfHash",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allHashes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrader", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashesOfCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashesOfTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfAllHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfHashesOfCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfHashesOfTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderOfHash",
    data: BytesLike
  ): Result;

  events: {
    "OrderCreated(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OrderCreated"): EventFragment;
}

export type OrderCreatedEvent = TypedEvent<[string] & { hash: string }>;

export class OrderBookMargin extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: OrderBookMarginInterface;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    createOrder(
      order: {
        loanId: BytesLike;
        leverageAmount: BigNumberish;
        loanTokenAddress: string;
        loanTokenSent: BigNumberish;
        collateralTokenSent: BigNumberish;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumberish;
        loanDataBytes: BytesLike;
        deadline: BigNumberish;
        createdTimestamp: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTrader(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { trader: string }>;

    hashesOfCollateralToken(
      collateralToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    hashesOfTrader(
      trader: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<[BigNumber]>;

    numberOfHashesOfCollateralToken(
      collateralToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    numberOfHashesOfTrader(
      trader: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    orderOfHash(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        number,
        string,
        string
      ] & {
        loanId: string;
        leverageAmount: BigNumber;
        loanTokenAddress: string;
        loanTokenSent: BigNumber;
        collateralTokenSent: BigNumber;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumber;
        loanDataBytes: string;
        deadline: BigNumber;
        createdTimestamp: BigNumber;
        v: number;
        r: string;
        s: string;
      }
    >;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  allHashes(
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  createOrder(
    order: {
      loanId: BytesLike;
      leverageAmount: BigNumberish;
      loanTokenAddress: string;
      loanTokenSent: BigNumberish;
      collateralTokenSent: BigNumberish;
      collateralTokenAddress: string;
      trader: string;
      minReturn: BigNumberish;
      loanDataBytes: BytesLike;
      deadline: BigNumberish;
      createdTimestamp: BigNumberish;
      v: BigNumberish;
      r: BytesLike;
      s: BytesLike;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTrader(hash: BytesLike, overrides?: CallOverrides): Promise<string>;

  hashesOfCollateralToken(
    collateralToken: string,
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  hashesOfTrader(
    trader: string,
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  numberOfAllHashes(overrides?: CallOverrides): Promise<BigNumber>;

  numberOfHashesOfCollateralToken(
    collateralToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  numberOfHashesOfTrader(
    trader: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  orderOfHash(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      number,
      string,
      string
    ] & {
      loanId: string;
      leverageAmount: BigNumber;
      loanTokenAddress: string;
      loanTokenSent: BigNumber;
      collateralTokenSent: BigNumber;
      collateralTokenAddress: string;
      trader: string;
      minReturn: BigNumber;
      loanDataBytes: string;
      deadline: BigNumber;
      createdTimestamp: BigNumber;
      v: number;
      r: string;
      s: string;
    }
  >;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    createOrder(
      order: {
        loanId: BytesLike;
        leverageAmount: BigNumberish;
        loanTokenAddress: string;
        loanTokenSent: BigNumberish;
        collateralTokenSent: BigNumberish;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumberish;
        loanDataBytes: BytesLike;
        deadline: BigNumberish;
        createdTimestamp: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    getTrader(hash: BytesLike, overrides?: CallOverrides): Promise<string>;

    hashesOfCollateralToken(
      collateralToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    hashesOfTrader(
      trader: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfHashesOfCollateralToken(
      collateralToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfHashesOfTrader(
      trader: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    orderOfHash(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        number,
        string,
        string
      ] & {
        loanId: string;
        leverageAmount: BigNumber;
        loanTokenAddress: string;
        loanTokenSent: BigNumber;
        collateralTokenSent: BigNumber;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumber;
        loanDataBytes: string;
        deadline: BigNumber;
        createdTimestamp: BigNumber;
        v: number;
        r: string;
        s: string;
      }
    >;
  };

  filters: {
    "OrderCreated(bytes32)"(
      hash?: BytesLike | null
    ): TypedEventFilter<[string], { hash: string }>;

    OrderCreated(
      hash?: BytesLike | null
    ): TypedEventFilter<[string], { hash: string }>;
  };

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createOrder(
      order: {
        loanId: BytesLike;
        leverageAmount: BigNumberish;
        loanTokenAddress: string;
        loanTokenSent: BigNumberish;
        collateralTokenSent: BigNumberish;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumberish;
        loanDataBytes: BytesLike;
        deadline: BigNumberish;
        createdTimestamp: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTrader(hash: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    hashesOfCollateralToken(
      collateralToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashesOfTrader(
      trader: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfHashesOfCollateralToken(
      collateralToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfHashesOfTrader(
      trader: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    orderOfHash(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createOrder(
      order: {
        loanId: BytesLike;
        leverageAmount: BigNumberish;
        loanTokenAddress: string;
        loanTokenSent: BigNumberish;
        collateralTokenSent: BigNumberish;
        collateralTokenAddress: string;
        trader: string;
        minReturn: BigNumberish;
        loanDataBytes: BytesLike;
        deadline: BigNumberish;
        createdTimestamp: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTrader(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashesOfCollateralToken(
      collateralToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashesOfTrader(
      trader: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfHashesOfCollateralToken(
      collateralToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfHashesOfTrader(
      trader: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    orderOfHash(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
